name: Setup Node and run `npm ci`
description: Uses specified Node version and runs npm commands to set up the environment for REST API CI

inputs:
  node-version:
    description: 'Node version to use'
    default: 20.x

runs:
  using: "composite"

  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}

    - name: Regenerate package-lock.json with latest "next" versions
      run: |
        rm package-lock.json
        npm install --package-lock-only
        cat package-lock.json
      shell: bash

    - run: npm ci
      shell: bash

    - run: npm ls -a
      shell: bash
      continue-on-error: true
